project_id = "tlnjspsywycbudhewsfv"

[functions.get-upload-url]
verify_jwt = false

[functions.delete-photos]
verify_jwt = false

[functions.upload-photo]
verify_jwt = false

[functions.client-selection]
verify_jwt = false