project_id = "tlnjspsywycbudhewsfv"

[functions.delete-photos]
verify_jwt = false

[functions.gallery-access]
verify_jwt = false

[functions.client-selection]
verify_jwt = false

[functions.confirm-selection]
verify_jwt = false

[functions.b2-upload]
verify_jwt = false

[functions.gallery-create-payment]
verify_jwt = false

[functions.infinitepay-create-link]
verify_jwt = false

[functions.infinitepay-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.mercadopago-credits-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.mercadopago-check-payment]
verify_jwt = false
